### PR TITLE
Copying LICENSE from root to unified_analytics

### PR DESCRIPTION
**Pull request by eliasyishak**
image

Wasn't sure why the LICENSE was `unknown` on pub, maybe because I don't have a trailing newline?

### CODE REVIEW

**Comment by devoncarew** [comment]
> Wasn't sure why the LICENSE was `unknown` on pub, maybe because I don't have a trailing newline?

Hopefully that's not it - I'd imagine they do some normalization for whitespace? If that does turn out to be the case we should open at issue on dart-lang/pub-dev.

You can also diff against the license at https://github.com/dart-lang/yaml_edit/blob/main/LICENSE - we just published a new version of that last week and that license is being recognized.

Separately - I see a lot of unrelated commits in this PR. They're not a huge issue - they already exist on the main branch. But you probably want to adjust your workflow so we just end up with commits in PRs that we intend. That might be starting new branches off main? `git checkout main`, `git pull`, `git checkout -b my_new_branch`?

If you want to get down to one commit for this PR you can squash all your commits in your local branch and then force push here (not normally a good practice but probably what we want here).

**Comment by devoncarew** [comment]
Ah! I see the license as recognized now, so probably some latency on pub.dev:

Screenshot 2023-03-07 at 1 46 39 PM

That could be worth filing an issue about :)

**Comment by eliasyishak** [comment]
> Ah! I see the license as recognized now, so probably some latency on pub.dev:
> 
> Screenshot 2023-03-07 at 1 46 39 PM
> 
> That could be worth filing an issue about :)

Ah yes, it must have slightly been delayed then, I didn't give it much time to check honestly.

**Comment by eliasyishak** [comment]
> > Wasn't sure why the LICENSE was `unknown` on pub, maybe because I don't have a trailing newline?
> 
> Hopefully that's not it - I'd imagine they do some normalization for whitespace? If that does turn out to be the case we should open at issue on dart-lang/pub-dev.
> 
> You can also diff against the license at https://github.com/dart-lang/yaml_edit/blob/main/LICENSE - we just published a new version of that last week and that license is being recognized.
> 
> Separately - I see a lot of unrelated commits in this PR. They're not a huge issue - they already exist on the main branch. But you probably want to adjust your workflow so we just end up with commits in PRs that we intend. That might be starting new branches off main? `git checkout main`, `git pull`, `git checkout -b my_new_branch`?
> 
> If you want to get down to one commit for this PR you can squash all your commits in your local branch and then force push here (not normally a good practice but probably what we want here).

Got it, I have been noticing for some reason all of the previous commits for some reason, I'm going to close this issue and try to test with a draft

**Pull request closed without merging**
