### PR TITLE
update to the latest package:dart_flutter_team_lints

### PR DESCRIPTION
**Pull request by devoncarew**
- update to the latest package:dart_flutter_team_lints

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by devoncarew** [comment]
It looks like this may be a bug in the lint:

> info - lib/src/registry.dart:13:13 - The referenced name isn't visible in scope. Try adding an import for the referenced name. - comment_references

from:

Screenshot 2023-09-28 at 12 37 27 PM

**Comment by devoncarew** [comment]
Looks like the above issue is covered by https://github.com/dart-lang/linter/issues/4645.

**Review by jonasfj — APPROVED** [review]
Curious, why all the `const`?

It's not like I'd care if these are constant or not, it just seems unnecessary.

**Comment by devoncarew** [comment]
> Curious, why all the `const`?
> 
> It's not like I'd care if these are constant or not, it just seems unnecessary.

It's from this line - `prefer_const_constructors`; very useful for flutter code and perf for widget trees. Sort of useful for regular dart code for communicating intent? There was some discussion [here](https://github.com/dart-lang/ecosystem/pull/167) (when we added it to package:dart_flutter_team_lints). It's not one I' very invested in; the changes aren't _bad_, they're just not very necessary.

**Pull request merged**
