### PR TITLE
Update USAGE_GUIDE to update the `flutterChannelCount` key in `LogFileStats`

### PR DESCRIPTION
**Pull request by eliasyishak**
Fixes the guide to be in line with the current state

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by eliasyishak** [comment]
@athomas would it preferred to just merge in a small change to kick the gob job again?

**Comment by eliasyishak** [comment]
@christopherfujino the context behind this small change is [here](https://chat.google.com/room/AAAAtyvwZMA/QQF_hrFe81k/)

We are seeing some sync issues with the internal mirror for this repo so hoping that this commit will kick it back on

**Review by christopherfujino — APPROVED** [review]
This LGTM to kick the job. As a side note, we if we're not testing that the schema of this comment is correct, I'd prefer deleting it.

**Comment by eliasyishak** [comment]
> I'd prefer deleting it.

Yeah I think it's better deleted too now that I have added better dartdocs for each of the `LogFileStats` variables.

**Pull request merged**
