### PR TITLE
Sampling rate functionality added

### PR DESCRIPTION
**Pull request by eliasyishak**
This addresses part of the umbrella issue:
- https://github.com/dart-lang/tools/issues/81

This feature adds a utility function that can take two different strings and return a decimal value that we can compare against the sampling rate found in the remotely hosted metadata survey file (sample below)

```json
[
    {
        "uniqueId": "test_channel",
        "url": "https://google.qualtrics.com/jfe/form/SV_5gsB2EuG5Et5Yy2",
        "startDate": "2023-06-01T09:00:00-07:00",
        "endDate": "2023-06-30T09:00:00-07:00",
	"description": "Help improve Flutter's release builds with this 3-question survey!",
	"dismissForDays": "10",
	"moreInfoURL": "https://docs.flutter.dev/reference/crash-reporting",
	"samplingRate": "0.1",    <---- the newly generated decimal value will be compared against value
	"conditions": [
	    {
	        "field": "logFileStats.recordCount",
	        "operator": ">=",
	        "value": 1000
            }
	]
    }
]
```

Sample usage of the new utility function

```dart
/// Will use two strings to produce a double for applying a sampling
/// rate for [Survey] to be returned to the user
double sampleRate(String string1, String string2) {
  final int1 = string1.codeUnits.reduce((a, b) => a + b);
  final int2 = string2.codeUnits.reduce((a, b) => a + b);

  return ((int1 * int2) % 100) / 100;
}

// Very simplified example to show usage
void main() {
  final sampleRate = 0.30;

  final producedValue = sampleRate('string1', 'string2');
  // Suppose the above output was 0.25

  if (sampleRate >= producedValue) passSurveyToUser();  // sudo code
}
```

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by eliasyishak** [comment]
@bwilkerson any thoughts on how I implemented the algorithm to produce a decimal value to compare against a given survey's sampling rate?

**Comment by bwilkerson** [comment]
Sorry for the slow response.

I'm not sure that I have the context to understand what you're trying to accomplish (beyond the obvious intent of deciding when to display a survey). In particular, I don't understand what the 'sample rate' is suppose to represent.

**Comment by eliasyishak** [comment]
@bwilkerson this feature is part of the larger issue #81 which is to enable unified analytics to provide the user surveys based on the data found in the log file (which contains all the events sent from a client). This PR is for surveys that use a sampling rate for delivering surveys since we may not want to send it all users.

Examples of a survey for this is if we wanted to ask 15% of users about which flutter channel (master, stable, beta) they should experiment with based on their historical events in the log file. Does that help?

**Review by bwilkerson — APPROVED** [review]
Not sure how this produces the linear distribution we want, but it appears to do so, so lgtm.

**Pull request merged**
